Set up awesome books website
Piercel2022/awesome-books pull request #2
Opened 2022-07-05 14:19 UTC by Lasten-Ernest

This pull request is for setting up the book website. It contains the HTML code and plain JavaScript for adding and removing books. The information is then retained in local storage.

2022-07-05 17:04 UTC, FrederickMih requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

# To Highlights

- Linters checks are all passing :heavy_check_mark: 

## Required Changes ♻️

N/A

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 17:04 UTC, FrederickMih commented on README.md
> +> Description the project.
- [ ] Hi team, let's include the project description. Project description is very important because it provides the goals and objectives to be reached.

2022-07-05 17:04 UTC, FrederickMih commented on README.md
> +Contributions, issues, and feature requests are welcome!
- [ ] I think you should provide a link to the issue page of your project. Kindly take a look at this [template](https://github.com/microverseinc/readme-template), you will discover that there's a  link to the issue page of the project.

2022-07-05 17:04 UTC, FrederickMih commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Let's also include a link to the license page as seen in this [Microverse README](https://github.com/microverseinc/readme-template) template. This will ensure that your README is professionally documented.

2022-07-05 17:04 UTC, FrederickMih commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] The **Acknowledgments** header of [this template](https://github.com/microverseinc/readme-template) is missing in your README file. Kindly include it and move a step toward the approval of this project.

2022-07-05 17:04 UTC, FrederickMih commented on script/addRemoveBooks.js
> +Navigation();
- [ ] Kindly resolve these console errors: 

![Screenshot from 2022-07-05 17-59-49](https://user-images.githubusercontent.com/63087491/177379319-93c373a3-4961-41df-b15c-66a4020933df.png)

2022-07-05 20:46 UTC, Piercel2022 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
@Lasten-Ernest I just fix this now

2022-07-05 20:53 UTC, Piercel2022 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
Fixed

2022-07-05 21:01 UTC, Piercel2022 commented on README.md
> +Contributions, issues, and feature requests are welcome!
Issues Link added

2022-07-06 02:08 UTC, Lasten-Ernest commented on README.md
> +This project is [MIT](./MIT.md) licensed.
@Piercel2022  Alright, thanks.

2022-07-06 02:16 UTC, Lasten-Ernest commented on README.md
> +This project is [MIT](./MIT.md) licensed.
@FrederickMih 
I fixed the issue in the JavaScript code.

2022-07-06 02:30 UTC, AnselemOdims approved these changes
### Hi  team🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 03:56 UTC, merged